// MOCK - Replace with Nilay's AI signal service when available
/**
 * Mock Signal Provider
 * Simulates AI / Trend Analysis signals generated by Nilay's module.
 * Integrates real stock market CSV dataset prices from csvStockService.
 */

const csvStockService = require('../services/csvStockService');

class MockSignalProvider {
  /**
   * Returns a simulated AI signal using actual prices from the CSV files provided by Nilay/User
   */
  getSignal(symbol = 'TCS', action = 'BUY', quantity = 10) {
    const cleanSymbol = symbol.toUpperCase();
    const actUpper = action.toUpperCase();
    const price = csvStockService.getLatestPrice(cleanSymbol);

    return {
      symbol: cleanSymbol,
      action: actUpper,
      price,
      quantity: actUpper === 'HOLD' ? 0 : quantity,
      signal: actUpper,
      timestamp: new Date().toISOString()
    };
  }

  /**
   * Generates a custom signal using CSV price as default if price not provided
   */
  generateCustomSignal({ symbol = 'TCS', action = 'BUY', price, quantity = 10, signal }) {
    const cleanSymbol = symbol.toUpperCase();
    const actUpper = action.toUpperCase();
    const actualPrice = typeof price === 'number' ? price : csvStockService.getLatestPrice(cleanSymbol);

    return {
      symbol: cleanSymbol,
      action: actUpper,
      price: actualPrice,
      quantity: actUpper === 'HOLD' ? 0 : quantity,
      signal: signal || actUpper,
      timestamp: new Date().toISOString()
    };
  }
}

module.exports = new MockSignalProvider();
